name: Terraform Provider Tests

on:
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**.go'
      - 'go.mod'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -o dist/terraform-provider-zoom .
      - run: go fmt ./...
      - name: Check no diff
        run: |
          git add .
          git diff --cached --exit-code
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs:
      - build
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - run:  make test TESTARGS="-cover ./..."
  acceptance:
    name: Acceptance Tests (Terraform ${{ matrix.terraform-version }})
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        terraform-version:
          - '1.5.*'
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: ${{ matrix.terraform-version }}
          terraform_wrapper: false
      - run: make testacc TESTARGS="-cover ./..."
        env:
          ZOOM_ACCOUNT_ID: ${{ secrets.ZOOM_ACCOUNT_ID }}
          ZOOM_CLIENT_ID: ${{ secrets.ZOOM_CLIENT_ID }}
          ZOOM_CLIENT_SECRET: ${{ secrets.ZOOM_CLIENT_SECRET }}
  summary:
    name: Summary
    runs-on: ubuntu-latest
    needs:
      - build
      - unit
      - acceptance
    timeout-minutes: 5
    permissions: {}
    if: ${{ always() }}
    steps:
      - name: Success
        run: |-
            for status in ${{ join(needs.*.result, ' ') }}
            do
              if [ "$status" != "success" ] && [ "$status" != "skipped" ]
              then
                echo "Some checks failed"
                exit 1
              fi
            done
